apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: "app-slug"
  labels:
    app.kubernetes.io/name: "app-slug"
    app.kubernetes.io/version: "1.0.0"
spec:
  selector:
    matchLabels:
     app.kubernetes.io/name: "app-slug"
  descriptor:
    links:
      - description: "Go to Redis_Insight"
        url: http://redisinsight-svc
