apiVersion: v1
kind: Service
metadata:
  name: redisinsight-svc
  labels:
    app: redisinsight
spec:
  ports:
  - name: redisinsight-tcp
    port: 80
    targetPort: 8001
  selector:
    app: redisinsight
  type: ClusterIP