apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  labels:
    app: redisdb
spec:
  ports:
  - name: redis-tcp
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redisdb
  type: ClusterIP